### ISSUE TITLE
How to read & write files of NodeMCU in Windows

### ISSUE THREAD

**Issue by HansungPark** [weyoui/OpenCaster#2]
- [x] : Find the solutions to read & write files of NodeMCU in Windows.
- [x] : Find the python commands to read & write files of NodeMCU directly.

**Comment by HansungPark** [comment]
I have uploaded in 'Wiki'. Please refer to that.

**Comment by ghost** [comment]
Great job! 
I would like to make a separate page on this information.
Please press "New Page" button in the Wiki page. :)
