### ISSUE TITLE
Elect project leader

### ISSUE THREAD

**Issue by ghost** [weyoui/OpenCaster#27]
We need to elect this project (OpenCaster) leader.

The leader will do the following tasks.
 - Lead the project and encourage the members
 - Manage the tickets
 - Manage the membership fees (to buy electronics parts, boards, etc)
      For example, we could send 50000 Won into leader's bank account and leader could buy items that are necessary to proceed project. And leader will report the progress and receipts at the end of project

**Comment by HansungPark** [comment]
Thank you for picking me up !
I will decide the proper membership fee later after consideration.
